org: abdelrahmantarek97
app: fk-task
service: fk-task

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

plugins:
  - serverless-offline

functions:
  api:
    handler: ./functions/user.handler
    events:
      - http:
          path: /user/{proxy+}
          method: ANY